version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

  embeddings:
    image: sivachandan1996/menu-genie-embeddings:latest
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/embed-items"]
      interval: 10s
      timeout: 5s
      retries: 3

  user-chat-backend:
    image: sivachandan1996/menu-genie-user-chat-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - qdrant
      - embeddings
      - redis

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: --interval 30

volumes:
  redis-data:
